### ISSUE TITLE
gcov_to_es not working

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#22]
I am not sure what is happening here.  "grcov" on the command line does not work after using the installation script; maybe some path must be added.  If it is grcov that gets executed, then more detail about the failure would be nice.

    ubuntu@ip-172-31-0-167:~/ActiveData-ETL$ git checkout codecoverage-kyle
    ubuntu@ip-172-31-0-167:~/ActiveData-ETL$ export PYTHONPATH=.
    ubuntu@ip-172-31-0-167:~/ActiveData-ETL$ python activedata_etl/etl.py --settings=resources/settings/codecoverage/etl.json --key=tc.573778

```
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:34 - ETL Loop Test - "gcov_to_es.py:66" (process) - public/test_info//code-coverage-gcda.zip
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:34 - ETL Loop Test - "gcov_to_es.py:81" (process_gcda_artifact) - Processing gcda artifact public/test_info//code-coverage-gcda.zip
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:34 - ETL Loop Test - "gcov_to_es.py:84" (process_gcda_artifact) - Using temp dir: /tmp/tmpjYOgY5
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:34 - ETL Loop Test - "gcov_to_es.py:90" (process_gcda_artifact) - Fetching gcda artifact: http://queue.taskcluster.net/v1/task/FVOWmG_7S3iA4p3XtGRB3A/artifacts/public/test_info//code-coverage-gcda.zip
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:38 - ETL Loop Test - "gcov_to_es.py:93" (process_gcda_artifact) - Extracting gcda files to /tmp/tmpjYOgY5/ccov
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:40 - ETL Loop Test - "gcov_to_es.py:104" (process_gcda_artifact) - Downloading gcno artifact http://queue.taskcluster.net/v1/task/SVAbGNCOSE2GuZo76qVJ-w/artifacts/public/build/target.code-coverage-gcno.zip
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:40 - ETL Loop Test - "gcov_to_es.py:108" (process_gcda_artifact) - GCNO records will be attached to etl_key: tc.573778:57376963.96.3
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:01:42 - ETL Loop Test - "gcov_to_es.py:112" (process_gcda_artifact) - Extracting gcno files to /tmp/tmpjYOgY5/ccov
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:02:04 - ETL Loop Test - "gcov_to_es.py:151" (process_directory) - Timer start: Processing LCOV directory /tmp/tmpjYOgY5/ccov
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:02:04 - ETL Loop Test - "gcov_to_es.py:162" (process_directory) - Timer end  : Processing LCOV directory /tmp/tmpjYOgY5/ccov (took 0.017 seconds)
ip-172-31-0-167 (pid 19073) - 2017-03-09 22:02:04 - ETL Loop Test - "gcov_to_es.py:71" (process) -
Traceback (most recent call last):
  File "/home/ubuntu/ActiveData-ETL/activedata_etl/transforms/gcov_to_es.py", line 68, in process
    keys.extend(process_gcda_artifact(source_key, resources, destination, etl_header_gen, task_cluster_record, artifact))
  File "/home/ubuntu/ActiveData-ETL/activedata_etl/transforms/gcov_to_es.py", line 116, in process_gcda_artifact
    process_directory('%s/ccov' % tmpdir, destination, task_cluster_record, file_etl)
  File "/home/ubuntu/ActiveData-ETL/activedata_etl/transforms/gcov_to_es.py", line 152, in process_directory
    lcov_coverage = run_lcov_on_directory(source_dir)
  File "/home/ubuntu/ActiveData-ETL/activedata_etl/transforms/gcov_to_es.py", line 204, in run_lcov_on_directory
    proc = Popen(['grcov', directory_path], stdout=PIPE, stderr=fdevnull)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by marco-c** [comment]
Forgot to mention it, but I've released a new version. Are you using that (0.1.3)? Perhaps we should change the script to always download the latest version?

**Comment by marco-c** [comment]
Actually, I believe here the problem is that it doesn't find `grcov`. You should add it to the path before launching `python activedata_etl/etl.py`.

**Comment by marco-c** [comment]
I've changed the script to always download the latest version: https://github.com/marco-c/grcov/commit/cf665cb29b146947b24d62fe691c547e6c8a97f2.

You still need to add it to the PATH. If you want the script to install it to a directory that is already in the path (e.g. /usr/local/bin), please file an issue in the grcov repo.
